## K-means

In [1]:
import numpy as np

data = np.array([
    [1.0, 2.0],
    [1.5, 1.8],
    [2.0, 2.2],
    [8.0, 8.0],
    [8.5, 8.3],
    [9.0, 8.5],
    [0.5, 1.0],
    [9.5, 9.0]
])

In [4]:
data.shape

(8, 2)

In [3]:
data.tolist()

[[1.0, 2.0],
 [1.5, 1.8],
 [2.0, 2.2],
 [8.0, 8.0],
 [8.5, 8.3],
 [9.0, 8.5],
 [0.5, 1.0],
 [9.5, 9.0]]

In [14]:
k = 2
n = data.shape[0]
cluster = np.random.randint(0, 2, n)

In [ ]:
# if you want to select subset based on other index
# subset = X[:, col_labels == 1]

In [21]:
centroid = {}
for i in range(k):
    centroid[i] = data[cluster==i].mean(axis=0)

In [26]:
centroid[0].shape

(2,)

In [24]:
dists = np.zeros([n, k])

In [28]:
data[0,:].shape

(2,)

In [43]:
def distance(p1, p2):
    # both points are np.ndarray of dim 1
    # Euclidian distance
    dim = p1.shape[0]
    sum_square = 0
    for i in range(dim):
        sum_square += (p1[i] - p2[i])**2
    return np.sqrt(sum_square)

In [44]:
distance(centroid[0], data[0])

7.778335297478503

In [45]:
for i in range(n):
    for c in range(k):
        dists[i, c] = distance(centroid[c], data[i,:])

In [46]:
dists

array([[7.7783353 , 2.35849528],
       [7.53475282, 2.0862646 ],
       [6.89655711, 1.45      ],
       [1.45      , 6.89655711],
       [2.01804361, 7.46675967],
       [2.53031619, 7.97260936],
       [8.81206559, 3.36340601],
       [3.23303263, 8.67827748]])

In [47]:
for i in range(n):
    min_idx = 0
    for c in range(k):
        if dists[i, c] < dists[i, min_idx]:
            min_idx = c
        cluster[i] = min_idx

In [48]:
cluster

array([1, 1, 1, 0, 0, 0, 1, 0])

In [50]:
dists.argmin(axis=1)

array([1, 1, 1, 0, 0, 0, 1, 0])

In [51]:
np.zeros(2)

array([0., 0.])

In [61]:
# putting all together
def k_means(data, k, max_iter = 10):
    # data is np.ndarray with dim 0 of n
    # k is number of clusters
    n = data.shape[0]
    
    # random initialize cluster
    cluster = np.random.randint(0, 2, n)

    # compute centroids
    centroids = {}
    for c in range(k):
        centroids[c] = data[cluster==c].mean(axis=0)

    dists = np.zeros([n, k])
    
    for _ in range(max_iter):
        for i in range(n):
            for c in range(k):
                dists[i,c] = distance(data[i,:], centroids[c])
        
        new_cluster = dists.argmin(axis=1)
        
        if np.all(new_cluster == cluster):
            break
        cluster = new_cluster
    return cluster, centroids
    
def distance(p1, p2):
    # both points are np.ndarray of dim 1
    # Euclidian distance
    dim = p1.shape[0]
    sum_square = 0
    for i in range(dim):
        sum_square += (p1[i] - p2[i])**2
    return np.sqrt(sum_square)

In [62]:
cluster, centroids = k_means(data, 2)

In [63]:
centroids

{0: array([4.75, 4.9 ]), 1: array([5.08333333, 5.16666667])}

In [64]:
# try again
import numpy as np

data = np.array([
    [1.0, 2.0],
    [1.5, 1.8],
    [2.0, 2.2],
    [8.0, 8.0],
    [8.5, 8.3],
    [9.0, 8.5],
    [0.5, 1.0],
    [9.5, 9.0]
])

In [65]:
n, d = data.shape

In [77]:
cluster = np.random.randint(0, d, (n,))

In [93]:
cluster

array([0, 1, 0, 0, 0, 1, 0, 1])

In [81]:
data[cluster == 1, :]

array([[1.5, 1.8],
       [9. , 8.5],
       [9.5, 9. ]])

In [82]:
centroids = {}
for c in range(d):
    centroids[c] = data[cluster == c, :].mean(axis=0)

In [89]:
def distance(p1, p2):
    return np.sqrt(np.sum(p1-p2)**2)

In [90]:
dists = np.zeros((n, d))
for i in range(n):
    for c in range(d):
        dists[i,c] = distance(data[i], centroids[c])

In [92]:
np.argmin(dists, axis=1)

array([0, 0, 0, 1, 1, 1, 0, 1])

In [ ]:
for _ in range(100):
    centroids = {}
    for c in range(d):
        centroids[c] = data[cluster == c, :].mean(axis=0)

    dists = np.zeros(n, d)
    for i in range(n):
        for c in range(d):
            dists[i,c] = distance(data[i], centorids[c])

    cluster = np.argmin(dists, axis=1)

In [105]:
def k_means(data, k=2, max_iter=100):
    n, d = data.shape
    cluster = np.random.randint(0, k, (n,))
    centroids = {}
    for _ in range(max_iter):
        centroids = {}
        for c in range(d):
            centroids[c] = data[cluster == c, :].mean(axis=0)
    
        dists = np.zeros((n, k))
        for i in range(n):
            for c in range(d):
                dists[i,c] = distance(data[i], centroids[c])
    
        cluster = np.argmin(dists, axis=1)
    return cluster, centroids

In [106]:
cluster, centroids = k_means(data)

In [107]:
cluster

array([0, 0, 0, 1, 1, 1, 0, 1])

In [108]:
centroids

{0: array([1.25, 1.75]), 1: array([8.75, 8.45])}