In [2]:
# linear regression
import numpy as np

X = np.array([
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0]
])

y = np.array([3.0, 5.0, 7.0, 9.0, 11.0])  # y = 2x + 1

In [11]:
d = 1
W = np.random.randn(d)
b = np.random.randn(1)

In [12]:
X @ W+b

array([-0.24496126, -0.81548407, -1.38600689, -1.95652971, -2.52705253])

In [7]:
X.transpose().shape

(1, 5)

In [21]:
# with gradient descent
class LinearRegression:
    def __init__(self, lr=0.01, iteration=100):
        self.W = None
        self.b = None
        self.lr = lr
        self.iter = iteration
    
    def fit(self, X, y):
        n, d = X.shape[0], X.shape[1]
        # initialize
        self.W = np.random.randn(d)
        self.b = np.random.randn(1)
        for _ in range(self.iter):
            y_pred = X @ self.W + self.b
            
            grad_W = X.transpose() @ (y_pred - y) / n
            grad_b = 1/n * np.sum(y_pred-y, axis=0)
            self.W -= self.lr * grad_W
            self.b -= self.lr * grad_b
        
    
    def predict(self, X):
        return X @ self.W + self.b

In [22]:
linear_reg = LinearRegression()

In [23]:
linear_reg.fit(X,y)

In [24]:
linear_reg.W

array([2.00811943])

In [25]:
linear_reg.b

array([0.97064883])

In [26]:
linear_reg.predict(X)

array([ 2.97876826,  4.98688769,  6.99500712,  9.00312655, 11.01124598])

In [28]:
n = X.shape[0]

In [34]:
np.concatenate([X, np.ones((n,1))], axis = 1)

array([[1., 1.],
       [2., 1.],
       [3., 1.],
       [4., 1.],
       [5., 1.]])

In [41]:
# Closed from solution
class LinearReg:
    def __init__(self):
        self.W = None
        self.b = None
    
    def fit(self, X, y):
        n, d = X.shape
        X_ext = np.concatenate([X, np.ones((n,1))], axis=1)
        W_ext = np.linalg.inv(X_ext.transpose() @ X_ext) @ X_ext.transpose() @ y
        self.W = W_ext[:-1]
        self.b = W_ext[-1]
    
    def predict(self, X):
        return X @ self.W + self.b

In [42]:
linear_reg = LinearReg()

In [43]:
linear_reg.fit(X, y)

In [44]:
linear_reg.predict(X)

array([ 3.,  5.,  7.,  9., 11.])