In [1]:
# logistic regression
import numpy as np

X = np.array([
    [1.0, 2.0],
    [2.0, 1.0],
    [2.0, 3.0],
    [6.0, 5.0],
    [7.0, 8.0],
    [8.0, 6.0]
])

y = np.array([0, 0, 0, 1, 1, 1])

In [11]:
n, d = X.shape
W = np.random.randn(d)
b = np.random.randn(1)

In [7]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [12]:
y_prob = sigmoid(X @ W + b)

In [13]:
y_prob

array([0.5935066 , 0.91613887, 0.72551717, 0.9915497 , 0.98091481,
       0.99872254])

In [15]:
(y_prob > 0.5).astype(int)

array([1, 1, 1, 1, 1, 1])

In [39]:
class LogisticRegression:
    def __init__(self, lr = 0.01, iter = 1000):
        self.W = None
        self.b = None
        self.lr = lr
        self.iter = iter

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    
    def fit(self, X, y):
        n, d = X.shape
        # initialize
        self.W = np.random.randn(d)
        self.b = np.random.randn(1)

        # update
        for _ in range(self.iter):
            y_prob = self._sigmoid(X @ self.W + self.b)
            dW = - 1 / n * X.T @ (y - y_prob)
            db = - 1 / n * np.sum(y - y_prob)

            self.W -= self.lr * dW
            self.b -= self.lr * db
            

    def predict(self, X):
        y_prob = self._sigmoid(X @ self.W + self.b)
        return (y_prob > 0.5).astype(int)
        
    def predict_proba(self, X):
        return self._sigmoid(X @ self.W + self.b)

In [40]:
logistic_regression = LogisticRegression()

In [41]:
logistic_regression.fit(X, y)

In [42]:
y_pred = logistic_regression.predict(X)

In [43]:
y_pred

array([0, 0, 0, 1, 1, 1])

In [44]:
y_proba = logistic_regression.predict_proba(X)

In [45]:
y_proba

array([0.16738309, 0.36647519, 0.27665213, 0.88342464, 0.90505227,
       0.97120866])