In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_california_housing

In [4]:
housing = fetch_california_housing(as_frame = True)

In [5]:
df = housing.frame

In [6]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422


In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


In [8]:
df.describe().round(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00
mean,3.87,28.64,5.43,1.10,1425.48,3.07,35.63,-119.57,2.07
std,1.90,12.59,2.47,0.47,1132.46,10.39,2.14,2.00,1.15
min,0.50,1.00,0.85,0.33,3.00,0.69,32.54,-124.35,0.15
25%,2.56,18.00,4.44,1.01,787.00,2.43,33.93,-121.80,1.20
50%,3.53,29.00,5.23,1.05,1166.00,2.82,34.26,-118.49,1.80
75%,4.74,37.00,6.05,1.10,1725.00,3.28,37.71,-118.01,2.65
max,15.00,52.00,141.91,34.07,35682.00,1243.33,41.95,-114.31,5.00


In [9]:
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

In [10]:
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25


In [11]:
y.head()

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_tmp, y_train, y_tmp = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
X_val, X_test, y_val, y_test = train_test_split(X_tmp, y_tmp, test_size=0.5, random_state=42)

In [15]:
print(len(X_train))
print(len(X_val))
print(len(X_test))

14448
3096
3096


In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
X_train_scaled = scaler.fit_transform(X_train)

In [19]:
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [20]:
pd.Series(X_train_scaled.mean(axis=0), index=X.columns).round(5).to_dict()

{'MedInc': 0.0,
 'HouseAge': -0.0,
 'AveRooms': -0.0,
 'AveBedrms': -0.0,
 'Population': 0.0,
 'AveOccup': 0.0,
 'Latitude': -0.0,
 'Longitude': -0.0}

In [21]:
pd.Series(X_train_scaled.std(axis=0), index=X.columns).round(4).to_dict()

{'MedInc': 1.0,
 'HouseAge': 1.0,
 'AveRooms': 1.0,
 'AveBedrms': 1.0,
 'Population': 1.0,
 'AveOccup': 1.0,
 'Latitude': 1.0,
 'Longitude': 1.0}

In [22]:
pd.Series(X_val_scaled.mean(axis=0), index=X.columns).round(5).to_dict()

{'MedInc': -0.02146,
 'HouseAge': 0.01635,
 'AveRooms': -0.03335,
 'AveBedrms': -0.02801,
 'Population': 0.00125,
 'AveOccup': -0.01532,
 'Latitude': -0.05636,
 'Longitude': 0.05634}

In [23]:
pd.Series(X_val_scaled.std(axis=0), index=X.columns).round(4).to_dict()

{'MedInc': 0.9736,
 'HouseAge': 1.0052,
 'AveRooms': 0.7313,
 'AveBedrms': 0.6647,
 'Population': 1.0433,
 'AveOccup': 0.0666,
 'Latitude': 0.9986,
 'Longitude': 0.9945}

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
from sklearn.pipeline import Pipeline

In [26]:
lr = LinearRegression()

In [27]:
lr.fit(X_train_scaled, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [28]:
y_pred_val = lr.predict(X_val_scaled)
y_pred_test = lr.predict(X_test_scaled)

In [29]:
pd.DataFrame({'Feature': X.columns, 'Coefficients': lr.coef_})

,Feature,Coefficients
0,MedInc,0.849222
1,HouseAge,0.122119
2,AveRooms,-0.299558
3,AveBedrms,0.348410
4,Population,-0.000884
5,AveOccup,-0.041698
6,Latitude,-0.893856
7,Longitude,-0.868617


In [30]:
y_val.values[:5]

array([1.225, 3.204, 4.507, 2.343, 1.019])

In [31]:
y_pred_val[:5]

array([1.37655112, 3.27141161, 3.94042122, 2.87266089, 1.98833994])

In [32]:
from sklearn.metrics import (
    mean_squared_error, 
    mean_absolute_error, 
    r2_score, 
    mean_absolute_error,
    mean_absolute_percentage_error
)

In [33]:
mean_squared_error(y_val, y_pred_val)

0.5408750691093342

In [34]:
mean_absolute_error(y_val, y_pred_val)

0.5334518974729614

In [35]:
r2_score(y_val, y_pred_val)

0.5848261822866255

In [36]:
mean_absolute_error(y_val, y_pred_val)

0.5334518974729614

In [37]:
mean_absolute_percentage_error(y_val, y_pred_val)

0.3215444663403093

In [38]:
from sklearn.model_selection import cross_validate, KFold

In [39]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)

In [40]:
pipe_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('reg', LinearRegression())
])

In [41]:
cv_result = cross_validate(
    pipe_lr,
    X_train,
    y_train,
    cv=cv,
    scoring=['neg_root_mean_squared_error', 'r2']
)

In [42]:
cv_result

{'fit_time': array([0.00246501, 0.00203896, 0.00221419, 0.00229597, 0.00198078]),
 'score_time': array([0.00071502, 0.00090694, 0.00094295, 0.00073814, 0.00080013]),
 'test_neg_root_mean_squared_error': array([-0.73145917, -0.74079427, -0.72898565, -0.71494259, -0.70695715]),
 'test_r2': array([0.61127907, 0.58190816, 0.58646706, 0.63255644, 0.62495045])}

In [43]:
cv_result['test_neg_root_mean_squared_error']

array([-0.73145917, -0.74079427, -0.72898565, -0.71494259, -0.70695715])

In [44]:
from sklearn.ensemble import RandomForestRegressor

In [45]:
pipe_rf = Pipeline([
    ('scaler', StandardScaler()),
    ('reg', RandomForestRegressor())
])

In [46]:
pipe_rf.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('scaler', ...), ('reg', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""squared_error"", ""absolute_error"", ""friedman_mse"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""friedman_mse"", which usesmean squared error with Friedman's improvement score for potentialsplits, ""absolute_error"" for the mean absolute error, which minimizesthe L1 loss using the median of each terminal node, and ""poisson"" whichuses reduction in Poisson deviance to find splits.Training using ""absolute_error"" is significantly slowerthan when using ""squared_error""... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 1.0 Poisson criterion.",'squared_error'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_sa

In [47]:
rf_model = pipe_rf.named_steps['reg']

In [48]:
importance_native = rf_model.feature_importances_

In [49]:
importance_native

array([0.52495309, 0.05338905, 0.04541989, 0.02956019, 0.03121584,
       0.13785308, 0.08841623, 0.08919264])

In [50]:
pd.Series(importance_native, index=X.columns)

MedInc        0.524953
HouseAge      0.053389
AveRooms      0.045420
AveBedrms     0.029560
Population    0.031216
AveOccup      0.137853
Latitude      0.088416
Longitude     0.089193
dtype: float64

In [51]:
from sklearn.inspection import permutation_importance

In [52]:
perm = permutation_importance(
    pipe_rf, X_val, y_val, n_repeats=10, random_state=42, scoring='r2'
)

In [53]:
pd.Series(perm.importances_mean, index=X.columns)

MedInc        0.735442
HouseAge      0.073440
AveRooms      0.025263
AveBedrms     0.008057
Population    0.006647
AveOccup      0.211206
Latitude      0.451583
Longitude     0.339677
dtype: float64

In [54]:
pd.Series(perm.importances_std, index=X.columns)

MedInc        0.014371
HouseAge      0.004938
AveRooms      0.001540
AveBedrms     0.001144
Population    0.001542
AveOccup      0.012331
Latitude      0.010859
Longitude     0.004728
dtype: float64

In [55]:
import shap

/Users/Larry.Jin/miniconda3/envs/prep/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [56]:
explainer = shap.TreeExplainer(rf_model)

In [57]:
# shap_values = explainer.shap_values(X_val)

In [58]:
from sklearn.model_selection import RandomizedSearchCV

In [62]:
from scipy.stats import randint
params = {
    'reg__n_estimators': randint(100, 500),
    'reg__max_depth': [None, 10, 15, 20],
    'reg__min_samples_split': randint(2, 20)
}

In [63]:
rs = RandomizedSearchCV(
    pipe_rf,
    params,
    n_iter=25,
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    scoring='neg_root_mean_squared_error',
    random_state=42,
    n_jobs=-1,
    refit=True
)

In [64]:
rs.fit(X_train, y_train)

/Users/Larry.Jin/miniconda3/envs/prep/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


,"estimator estimator: estimator objectAn object of that type is instantiated for each grid point.This is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",Pipeline(step...Regressor())])
,"param_distributions param_distributions: dict or list of dictsDictionary with parameters names (`str`) as keys and distributionsor lists of parameters to try. Distributions must provide a ``rvs``method for sampling (such as those from scipy.stats.distributions).If a list is given, it is sampled uniformly.If a list of dicts is given, first a dict is sampled uniformly, andthen a parameter is sampled using that dict as above.","{'reg__max_depth': [None, 10, ...], 'reg__min_samples_split': <scipy.stats....t 0x12b700690>, 'reg__n_estimators': <scipy.stats....t 0x12b3a4d90>}"
,"n_iter n_iter: int, default=10Number of parameter settings that are sampled. n_iter tradesoff runtime vs quality of the solution.",25
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.If None, the estimator's score method is used.",'neg_root_mean_squared_error'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given the ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``RandomizedSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validatio

In [65]:
rs.best_params_

{'reg__max_depth': None, 'reg__min_samples_split': 3, 'reg__n_estimators': 439}

In [66]:
rs.best_score_

np.float64(-0.5178778389433422)

In [72]:
best = rs.best_estimator_
y_test_pred = best.predict(X_test)

In [73]:
mean_squared_error(y_test, y_test_pred)

0.2399368365992177

In [75]:
mean_absolute_error(y_test, y_test_pred)

0.3232548361329721

In [76]:
r2_score(y_test, y_test_pred)

0.8185472694242852

In [77]:
mean_absolute_percentage_error(y_test, y_test_pred)

0.18713867562227554